blogpost: MNIST Demo
knmlprz/knml.edu.pl pull request #14
Opened 2023-08-30 12:31 UTC by kosiarn

2023-08-30 14:08 UTC, pgronkievitz commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +Konwolucja polega na pewnego rodzaju kompresji informacji z kilku punktów(lub, jak w naszym przypadku, pikseli) za pomocą sumy ważonej:
Warto wspomnieć, że inaczej to splot

```suggestion
Konwolucja polega na pewnego rodzaju kompresji informacji z kilku punktów (lub, jak w naszym przypadku, pikseli) za pomocą sumy ważonej:
```

2023-08-30 14:09 UTC, pgronkievitz commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +Całą aplikację stworzyliśmy w Pythonie; jest jednym z najpopularniejszych języków używanych do analizy danych i uczenia maszynowego oraz z pomocą nieoficjalnych modułów pozawala na tworzenie prostych
Ludzie nie potrafią w średniki, na luzie można je zastąpić kropką w większości przypadków
```suggestion
Całą aplikację stworzyliśmy w Pythonie. Jest jednym z najpopularniejszych języków używanych do analizy danych i uczenia maszynowego oraz z pomocą nieoficjalnych modułów pozawala na tworzenie prostych intefejsów.
```

2023-08-30 14:10 UTC, pgronkievitz commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +Artykuł[^1], z którego pochodzi powyższa animacja, świetnie opisuje cały koncept.
Opisz ją i zalinkuj jako źródło

2023-08-30 14:11 UTC, pgronkievitz commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +Demo[^2] ze strony *setosa.io* pozwala na eksperymentowanie z maskami konwolucyjnymi.
```suggestion
Demo[^2] ze strony [setosa.io](https://setosa.io) pozwala na eksperymentowanie z maskami konwolucyjnymi.
```

2023-08-30 14:12 UTC, pgronkievitz commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +- **Funkcja ReLU**(**Re**ctified **L**inear **U**nit): Funkcja aktywacji zerująca liczby ujemne.
```suggestion
- **Funkcja ReLU** (**Re**ctified **L**inear **U**nit): Funkcja aktywacji zerująca liczby ujemne.
```

2023-08-30 14:14 UTC, pgronkievitz commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +Pierwszym z nich była odwrócona paleta kolorów: zestaw MNIST zawiera obrazy cyfr narysowanych białym kolorem na czarnym tle, natomiast kanwa w naszym interfejsie stosowała odwrotną kolorystykę. Powod
```suggestion
Pierwszym z nich była odwrócona paleta kolorów: zestaw MNIST zawiera obrazy cyfr narysowanych białym kolorem na czarnym tle, natomiast kanwa w naszym interfejsie stosowała odwrotną kolorystykę. Powodowało to zadowalającą dokładność modelu podczas treningu oraz słabą dokładność podczas testowania go w aplikacji. Rozwiązanie było proste - wystarczyło przetworzyć obrazek pobierany od użytkownika, odwracając w nim kolory.
```

2023-08-31 05:46 UTC, kosiarn commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +Konwolucja polega na pewnego rodzaju kompresji informacji z kilku punktów(lub, jak w naszym przypadku, pikseli) za pomocą sumy ważonej:
done!

2023-08-31 05:46 UTC, kosiarn commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +Całą aplikację stworzyliśmy w Pythonie; jest jednym z najpopularniejszych języków używanych do analizy danych i uczenia maszynowego oraz z pomocą nieoficjalnych modułów pozawala na tworzenie prostych
done!

2023-08-31 05:47 UTC, kosiarn commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +Artykuł[^1], z którego pochodzi powyższa animacja, świetnie opisuje cały koncept.
done!

2023-08-31 05:47 UTC, kosiarn commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +Demo[^2] ze strony *setosa.io* pozwala na eksperymentowanie z maskami konwolucyjnymi.
done

2023-08-31 05:47 UTC, kosiarn commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +- **Funkcja ReLU**(**Re**ctified **L**inear **U**nit): Funkcja aktywacji zerująca liczby ujemne.
done

2023-08-31 05:48 UTC, kosiarn commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +Zgodnie z nazwą projektu, przetrenowaliśmy model na zestawie MNIST[^4]. Podczas wstępnych testów napotkaliśmy kilka problemów polegających na różnicach między zestawem uzytym do treningu a danymi, kt
done

2023-08-31 05:48 UTC, kosiarn commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +Pierwszym z nich była odwrócona paleta kolorów: zestaw MNIST zawiera obrazy cyfr narysowanych białym kolorem na czarnym tle, natomiast kanwa w naszym interfejsie stosowała odwrotną kolorystykę. Powod
done

2023-08-31 05:49 UTC, kosiarn commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +Drugi problem był nieco bardziej skomplikowany. Obszar do rysowania dany użytkownikowi pozwalał mu na rysowanie cyfr dowolnej wielkości i w dowolnym miejscu (małe, duże, bliżej któregoś rogu kanwy et
done!

2023-08-31 18:15 UTC, finloop requested changes
1. Znalazłem kilka literówek — to jest must have do poprawy.
2. Co do pozostałych (opcjonalnych) propozycji, zadecyduj czy je wprowadzić i oznacz mnie, jak skończysz, to zaakceptuję pr.

PS: Dobry artykuł, super animacje 😁✨ i obrazki 🖼️

2023-08-31 18:15 UTC, finloop commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +Podczas przeprowadzania konwolucji obraz traktuje się jako zbiór macierzy zawierających wartości kolorów dla odpowiednich pikseli - może to być na przykład zbiór macierzy wartości RGB lub macierz odc
```suggestion
Podczas przeprowadzania konwolucji obraz traktuje się jak macierz, której komórkami są kolorowe piksele. Obraz można zapisać jako trzy macierze RGB (jedna dla każdego z kanałów) lub macierz odcieni szarości.
```

2023-08-31 18:15 UTC, finloop commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +Do zaimplementowania modelu użyliśmy biblioteki PyTorch - posiada ona zdefiniowane wastwy neuronów oraz konwolucyjne, co ułatwiło zbudowanie architektury.
```suggestion
Do zaimplementowania modelu użyliśmy biblioteki PyTorch - posiada ona zdefiniowane warstwy neuronów oraz konwolucyjne, co ułatwiło zbudowanie architektury.
```

2023-08-31 18:15 UTC, finloop commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +- **Dropout**: Losowe zerowanie wartości z pewnym pradwopodobieństwem. Operacja ta utrudnia przeuczenie modelu m.in. w przypadku małego zestawu danych treningowych.
```suggestion
- **Dropout**: Losowe zerowanie wartości z pewnym prawdopodobieństwem. Operacja ta utrudnia przeuczenie modelu m.in. w przypadku małego zestawu danych treningowych.
```

2023-08-31 18:15 UTC, finloop commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +Drugi problem był nieco bardziej skomplikowany. Obszar do rysowania dany użytkownikowi pozwalał mu na rysowanie cyfr dowolnej wielkości i w dowolnym miejscu (małe, duże, bliżej któregoś rogu kanwy et
```suggestion
Drugi problem był nieco bardziej skomplikowany. Obszar do rysowania dany użytkownikowi pozwalał mu na rysowanie cyfr dowolnej wielkości i w dowolnym miejscu (małe, duże, bliżej któregoś rogu kanwy etc.), co zmniejszało dokładność modelu (zestaw MNIST posiada cyfry o podobnej do siebie wielkości). Na szczęście członek naszego koła, [Vitalii Morskyi](https://github.com/FrightenedFox) przygotował wcześniej rozwiązanie - funkcja `prepare_image()` z repozytorium *handwritten-digits*[^5] dostosowuje obrazek do formatu bardziej przypominającego ten z zestawu treningowego naszego modelu. Funkcję tę należało zastosować zarówno przy klasyfikacji, jak i przy treningu - ustandaryzowało to dane treningowe, co zwiększyło dokładność modelu.
```

2023-08-31 18:15 UTC, finloop commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +W dalszej części porzuciliśmy plan z wizualizacją sieci na rzecz prostszego interfejsu przystosowanego na urządzenia mobilne oraz zmieniliśmy technologię z Gradio na rzecz Streamlit z powodów błędów
```suggestion
Ostatecznie porzuciliśmy plan wizualizacji sieci na rzecz prostszego interfejsu dostosowanego do urządzeń mobilnych oraz zmieniliśmy technologię z Gradio na Streamlit ze względu na błędy występujące podczas tworzenia kanwy.
```

2023-08-31 18:15 UTC, finloop commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +Całą aplikację stworzyliśmy w Pythonie. Jest on jednym z najpopularniejszych języków używanych do analizy danych i uczenia maszynowego oraz z pomocą nieoficjalnych modułów pozwala na tworzenie prosty
opcjonalne

2023-08-31 18:15 UTC, finloop commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +Postanowiliśmy użyć konwolucyjnej sieci neuronowej, ponieważ same sieci neuronowe są popularnym wyborem przy problemie klasyfikacji cyfr, a konwolucja często ułatwia zadania związane z przetwarzaniem
opcjonalne

2023-08-31 18:15 UTC, finloop commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +Podczas przeprowadzania konwolucji obraz traktuje się jako zbiór macierzy zawierających wartości kolorów dla odpowiednich pikseli - może to być na przykład zbiór macierzy wartości RGB lub macierz odc
opcjonalne

2023-08-31 18:15 UTC, finloop commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +W dalszej części porzuciliśmy plan z wizualizacją sieci na rzecz prostszego interfejsu przystosowanego na urządzenia mobilne oraz zmieniliśmy technologię z Gradio na rzecz Streamlit z powodów błędów
opcjonalne

2023-08-31 18:18 UTC, finloop commented
A i ostatnia ważna rzecz, brakuje linku do demo! Z tego co wiem to apka jest dostępna na streamlicie.

2023-08-31 18:49 UTC, finloop submitted a review, later dismissed
Poprawiłem jedną literówkę, LGTM

2023-08-31 18:53 UTC, finloop requested changes

2023-08-31 18:53 UTC, finloop commented on content/blog/mnist-demo-jak-komputer-widzi-tekst/index.md
> +date: 2023-08-24T12:00:00+02:00
```suggestion
date: 2023-08-30T12:00:00+02:00
```

2023-08-31 18:54 UTC, finloop approved these changes

2023-08-31 18:54 UTC, merged